=== Knowy-Learn/knowy/modules/infrastructure/xml-data-loader/src/test/resources/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:int"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="value" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Knowy-Learn/knowy/modules/infrastructure/xml-data-loader/src/test/resources/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data.xsd">
	<item>
		<id>1</id>
		<name>Item One</name>
		<value>Value One</value>
	</item>
	<item>
		<id>2</id>
		<name>Item Two</name>
		<value>Value Two</value>
	</item>
	<item>
		<id>3</id>
		<name>Item Three</name>
		<value>Value Three</value>
	</item>
</items>
